config/routes.rb
Rails.application.routes.draw do

  mount Flip::Engine => "/flip"

  devise_for :users
  resources :users, :only => [:show]
  

  devise_for :admins
  resources :posts
  resources :categories
  resources :comments
  resources :basecamps

  root "posts#index"

  get 'dashboard' => 'dashboard#index'

  get 'team' => 'pages#team'
  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/basecamp.rb
class Basecamp < ActiveRecord::Base
	
	def to_s
		"#{text}"
	end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :terms
	has_many :songs, :through => :terms

	def to_s
		title
	end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	validates :content, presence: true, length: {minimum: 4}
	belongs_to :song
	belongs_to :user

	def to_s
		"'#{content[0,15]}..' by user '#{user}"
	end

end

app/models/feature.rb
class Feature < ActiveRecord::Base
  extend Flip::Declarable

  strategy Flip::CookieStrategy
  strategy Flip::DatabaseStrategy
  strategy Flip::DeclarationStrategy
  default false

  feature :sign_up, default: true
  feature :sign_in, default: true

end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :title, presence: true
	validates :body, presence: true
    
  
  	
  	belongs_to :user
  	belongs_to :song
  	has_many :posts

	def to_s
		"#{title}"
	end

	def to_im
		"#{image_link}"
	end
	
	def to_param
		"#{id}-#{slug}"
	end

	def slug
		title.downcase.gsub(" ", "-")
	end

end

app/models/relative.rb
class Relative < ActiveRecord::Base
	belongs_to :song
	has_one :post
end

app/models/song.rb
class Song < ActiveRecord::Base
	validates :title, presence: true
	validates :artistn, presence: true
	validates :desc, presence: true
	validates :link, presence: true

	belongs_to :user
	has_many :comments, dependent: :destroy
	has_many :posts
	has_many :terms
	has_many :categories, :through => :terms

	def to_s
		title
	end

	def self.search(query)
		where("title like ?", "%#{query}%")
	end

	def to_param
		"#{id}-#{slug}"
	end

	def slug
		title.downcase.gsub(" ", "-")
	end

end

app/models/term.rb
class Term < ActiveRecord::Base
	
	belongs_to :category
	belongs_to :song

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments
  has_many :songs
  has_many :features

  validates :prname, presence: true
  validates :email, presence: true

  def to_s
    "#{prname}"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def team
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  require 'json'




  def create
    @song = Song.find(params[:song_id])
  	@post  = @song.posts.create(params[:post].permit(:title, :subtitle, :body, :link, :image_link))
    @post.user = current_user
    redirect_to song_path(@song)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  def edit
    @song = Song.find(params[:song_id])
    @post = @song.posts.edit(params)
  	#@post = Post.find(params[:id])
  end

  def update
  	@post = Post.find(params[:id])

  	if @post.update(post_params)
  		redirect_to @post
  	else
  		render 'edit'
  	end
  end

  private
  	def post_params
  		params.require(:post).permit(:title, :subtitle, :body, :link, :artist, :author)
  	end

    after_filter :set_access_control_headers

  def set_access_control_headers 
  headers['Access-Control-Allow-Origin'] = '*' 
  headers['Access-Control-Request-Method'] = '*' 
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def user_logged_in_msg
		str = ''
		str += '<div class="row">'
		str += '<div class="col-xs-12 col-md-3 hidden-xs"></div>'
		str +=  '<!-- left side -->  <div class="col-xs-12 col-md-6"><div class = "userloggedin">'
		
		if user_signed_in?
			str += "<p id = ""user_info"">Logged in as #{current_user}<br>#{link_to('Logout', destroy_user_session_path, :method => :delete)}</p>"
		else
			str += "<p id = ""user_info"">#{link_to('Login', new_user_session_path)} or #{link_to('Sign Up', new_user_registration_path)}</p>"
		end
		str += '</div>'
		str += '<div class="col-xs-12 col-md-3 hidden-xs"></div> <!-- right side --></div></div>'
		raw(str)
	end

	def admin_logged_in_msg
		str = ''
		str += '<div class="row">
		<div class="col-xs-12 col-md-2 hidden-xs"></div> <!-- left side -->
			<div class="col-xs-12 col-md-8"><div class = "adminloggedin">'
		if admin_signed_in?
			str += "<p id = ""user_info"">#{current_admin}<br>#{link_to('Logout', destroy_admin_session_path, :method => :delete)}</p>"
		
		end
		str += '</div><div class="col-xs-12 col-md-2 hidden-xs"></div> <!-- right side --></div></div>'
		raw(str)
	end

	

end

app/helpers/basecamp_helper.rb
module BasecampHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	def author_for_(post)
		raw("<div class=""post_details""> Review By: #{post.user} on #{post.created_at.strftime('%m-%d-%y')}</div>")
	end

	

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
	def author_(song)
		raw("<div class=""song_details""> Categories: #{song.categories.map { |c| link_to(c.title, c) }.join(', ')} <br> Curated By: #{song.user}  | #{link_to(pluralize(song.comments.size, 'Comment'), song_path(song, anchor: 'commentlabel'))}</div>")
	end

	def song_posting(song)
		raw("<div class = ""song_details""> #{song.posts.map{ |p| p.title}.join(', ')} </div>")
	end

	

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_form.html.erb
<%= form_for ([@song, @song.posts.build]) do |f| %>
 
  

  <div class="row">
    <div class="col-xs-12 col-md-10 col-md-offset-1 post-title-field form-field">
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title, placeholder: 'Awesome title here' %>
    </p>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-md-10 col-md-offset-1 post-title-field form-field">
    <p>
      <%= f.label :subtitle %><br>
      <%= f.text_field :subtitle, placeholder: 'Great subtitle here' %>
    </p>
      </div>
    </div>
 

   <div class="row">
    <div class="col-xs-12 col-md-10 col-md-offset-1 rad-textarea form-field">
    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </p>
      </div>
    </div>

   <div class="row">
    <div class="col-xs-12 col-md-10 col-md-offset-1 post-title-field form-field">
    <p>
      <%= f.label :embed %><br>
      <%= f.text_field :link, placeholder: 'Embed code here' %>
    </p>
     </div>
    </div>


    <div class="row">
      <div class="col-xs-12 col-md-10 col-md-offset-1 post-title-field form-field">
   <p>
      <%= f.label :image %><br>
      <%= f.text_field :image_link, placeholder: 'Link to Image' %> <!-- NEEDS TO BE FIXED [as of 0.1.1] -->
    </p>
       </div>
    </div>

    <div class="row">
    <div class="col-xs-12 col-md-1"></div> <!-- left side -->
      <div class="col-xs-12 col-md-10 submit-post-button">
    <p>
      <%= f.submit %>
    </p>
       </div>
    <div class="col-xs-12 col-md-1"></div> <!-- right side -->
    </div>

<% end %>

app/views/posts/_post.html.erb
<article class="post">


<div class="row fill">
	<div class="col-xs-12 col-md-12 post-image fill">
				<img src=<%=post.image_link %>>
	</div>
	</div>

	<div class="row">
		<div class="col-xs-12 col-md-2 hidden-xs"></div> <!-- left side -->
			<div class="col-xs-12 col-md-8 post-title">
				<%= post.title %>
			</div>
		<div class="col-xs-12 col-md-2 hidden-xs"></div> <!-- right side -->
	</div>

 
 	<div class="row">
		<div class="col-xs-12 col-md-2 hidden-xs"></div> <!-- left side -->
			<div class="col-xs-12 col-md-8 post-subtitle">
				<%= post.subtitle %> 
			</div>
		<div class="col-xs-12 col-md-2 hidden-xs"></div> <!-- right side -->
	</div>

 	<div class="row">
		<div class="col-xs-12 col-md-3 hidden-xs"></div> <!-- left side -->
			<div class="col-xs-12 col-md-6 post-body">
				<p><%= simple_format post.body %></p>
			</div>
		<div class="col-xs-12 col-md-3 hidden-xs"></div> <!-- right side -->
	</div>
	</div>
</article>

app/views/posts/_smallpost.html.erb
<% @posts.each do |p| %>

  <div class="date-container">
    <div class="day-name">  <%= p.created_at.strftime("%a") %> </div>
    <div class="month-name"> <%= p.created_at.strftime("%b") %> </div>
    <div class="day-number"> <%= p.created_at.strftime("%e") %> </div>
  </div>

  <h3 class="index-writing"><%= link_to p, post_path(p) %> 
  <br />
  
    <img src=<%=p.author %>>
    <h4> <%= p.subtitle %> </h4>
    <% if user_signed_in? %>
      <%= if currentid === p.user_id %>
        <%= link_to "Edit", edit_post_path(p) %>
        <%end%>
    <%end%>
    
      <% if admin_signed_in? %>
        <%= p.created_at %>
        <%= link_to 'Destroy', post_path(p), method: :delete, data: { confirm: 'Are you sure?' }%> 
      <%end%>
  </h3>

<% end %>

app/views/posts/edit.html.erb
<h1>Editing <%= @post.title %></h1>

<%= render 'form' %>

app/views/posts/index.html.erb
 	<div class="row">
	<div class="col-xs-12 col-md-12 underbar-thin">
	</div>
	</div> <!-- GIVES RADCIRCLE GRADIENT -->

 	<div class="row posts-index">
		<div class="col-xs-12 col-md-2 hidden-xs"></div> <!-- left side -->
			<div class="col-xs-12 col-md-8">
				<p><%= render partial: "smallpost" %></p>
			</div>
		<div class="col-xs-12 col-md-2 hidden-xs"></div> <!-- right side -->
	</div>

	<div class="row">
	<div class="col-xs-12 col-md-12 underbar-thin">
	</div>
	</div> <!-- GIVES RADCIRCLE GRADIENT -->

	<div class="row">
			<div class="col-xs-12 col-md-6 col-md-offset-3">
				<div class="col-xs-6 col-md-3">FB<i class="fa fa-facebook fa-5x"></i></div>
				<div class="col-xs-6 col-md-3">TW<i class="fa fa-twitter fa-5x"></i></div>
				<div class="col-xs-6 col-md-3">SC<i class="fa fa-soundcloud fa-5x"></i></div>
				<div class="col-xs-6 col-md-3">YT<i class="fa fa-youtube fa-5x"></i></div>
			</div>
	</div>

app/views/posts/new.html.erb
	<div class="row">
	<div class="col-xs-12 col-md-12 underbar">
	</div>
	</div>

	<div class="row">
			<div class="col-xs-12 col-md-8 col-md-offset-2 create-new-post">
				<h1>Create a work of art. Write something awesome.</h1>
			</div>
	</div>

<%= render partial: 'form' %>

app/views/posts/show.html.erb
	<div class="row fill">
	<div class="col-xs-12 col-md-12 post-image fill">
				<img src=<%=@post.author %>>
	</div>
	</div>

	<!-- <div class="row">
			<div class="col-xs-12 col-md-6 col-md-offset-3 post-songtitle-songartist">
				<span><%=@post.artist%></span> <span>-</span> <span>"<%=@post.song%>"</span>
			</div>
	</div>	--> <!-- commented out the redundancy -->

	<div class="row">
		<div class="col-xs-12 col-md-12">
			<%= raw(@post.link) %> <!-- song link -->
		</div>
	</div>

	<div class="row">
		<div class="col-xs-12 col-md-2 hidden-xs"></div> <!-- left side -->
			<div class="col-xs-12 col-md-8 post-title">
				<%= @post.title %>
			</div>
		<div class="col-xs-12 col-md-2 hidden-xs"></div> <!-- right side -->
	</div>

	<div class="row">
	<div class="col-xs-12 col-md-12 underbar">
	</div>
	</div>

	<div class="row">
		<div class="col-xs-12 col-md-3 hidden-xs"></div> <!-- left side -->
			<div class="col-xs-12 col-md-6 post-author">
				<%= author_(@post) %>
			</div>
		<div class="col-xs-12 col-md-3 hidden-xs"></div> <!-- right side -->
	</div>
 
 	<div class="row">
		<div class="col-xs-12 col-md-2 hidden-xs"></div> <!-- left side -->
			<div class="col-xs-12 col-md-8 post-subtitle">
				<%= @post.subtitle %> 
			</div>
		<div class="col-xs-12 col-md-2 hidden-xs"></div> <!-- right side -->
	</div>

 	<div class="row">
		<div class="col-xs-12 col-md-3 hidden-xs"></div> <!-- left side -->
			<div class="col-xs-12 col-md-6 post-body">
				<p><%= simple_format @post.body %></p>
			</div>
		<div class="col-xs-12 col-md-3 hidden-xs"></div> <!-- right side -->
	</div>



<div class="row comments">
	<div class="col-xs-12 col-md-6 col-md-offset-3">

<section class ="comments">
	<h2> <i class="fa fa-comments-o fa-2x"></i> Comments: <span class="comment-number"><%= @post.comments.size %></span></h2>
	<%if user_signed_in? %>
		<%= render 'comments/form'%>
	<%else %>
		<p class="sign-in-to-comment">You must <%= link_to 'login', new_user_session_path %> to post comments</p>
	<%end%>
	<%= render partial: 'comments/comment', collection: @post.comments.order('created_at desc') %>
</section>

</div></div>