config/routes.rb
Rails.application.routes.draw do

  mount Flip::Engine => "/flip"

  devise_for :users
  resources :users, :only => [:show]
  

  devise_for :admins
  resources :posts
  resources :categories
  resources :comments
  resources :basecamps

  root "posts#index"

  get 'dashboard' => 'dashboard#index'

  get 'team' => 'pages#team'
  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/basecamp.rb
class Basecamp < ActiveRecord::Base
	
	def to_s
		"#{text}"
	end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :terms
	has_many :songs, :through => :terms

	def to_s
		title
	end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	validates :content, presence: true, length: {minimum: 4}
	belongs_to :song
	belongs_to :user

	def to_s
		"'#{content[0,15]}..' by user '#{user}"
	end

end

app/models/feature.rb
class Feature < ActiveRecord::Base
  extend Flip::Declarable

  strategy Flip::CookieStrategy
  strategy Flip::DatabaseStrategy
  strategy Flip::DeclarationStrategy
  default false

  feature :sign_up, default: true
  feature :sign_in, default: true

end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :title, presence: true
	validates :body, presence: true
    
  
  	
  	belongs_to :user
  	belongs_to :song
  	has_many :posts

	def to_s
		"#{title}"
	end

	def to_im
		"#{image_link}"
	end
	
	def to_param
		"#{id}-#{slug}"
	end

	def slug
		title.downcase.gsub(" ", "-")
	end

end

app/models/relative.rb
class Relative < ActiveRecord::Base
	belongs_to :song
	has_one :post
end

app/models/song.rb
class Song < ActiveRecord::Base
	validates :title, presence: true
	validates :artistn, presence: true
	validates :desc, presence: true
	validates :link, presence: true

	belongs_to :user
	has_many :comments, dependent: :destroy
	has_many :posts
	has_many :terms
	has_many :categories, :through => :terms

	def to_s
		title
	end

	def self.search(query)
		where("title like ?", "%#{query}%")
	end

	def to_param
		"#{id}-#{slug}"
	end

	def slug
		title.downcase.gsub(" ", "-")
	end

end

app/models/term.rb
class Term < ActiveRecord::Base
	
	belongs_to :category
	belongs_to :song

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments
  has_many :songs
  has_many :features

  validates :prname, presence: true
  validates :email, presence: true

  def to_s
    "#{prname}"
  end
end

app/helpers/basecamp_helper.rb
module BasecampHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	def author_for_(post)
		raw("<div class=""post_details""> Review By: #{post.user} on #{post.created_at.strftime('%m-%d-%y')}</div>")
	end

	

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
	def author_(song)
		raw("<div class=""song_details""> Categories: #{song.categories.map { |c| link_to(c.title, c) }.join(', ')} <br> Curated By: #{song.user}  | #{link_to(pluralize(song.comments.size, 'Comment'), song_path(song, anchor: 'commentlabel'))}</div>")
	end

	def song_posting(song)
		raw("<div class = ""song_details""> #{song.posts.map{ |p| p.title}.join(', ')} </div>")
	end

	

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Peak</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="http://netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>

<div class="row search-bar">
	<div class="col-xs-12 col-md-10 col-md-offset-1">
		<%= form_tag(posts_path, :method => "get") do %>
			<div class="search-bar">
				<%= text_field_tag :search, params[:search], placeholder: "Search for something" %>
			</div>
		<%end%>
	</div>
</div>

<div class="row navigation-bar">
			<div class="col-xs-12 col-md-10 col-md-offset-1 navigation-bar">

				<%= link_to root_path, id: "logo" do %>
  				<i class="fa fa-home fa-5x home-btn"></i>
          		<h1>Radcircle</h1>
				<% end %>

					
					<h2><a href="http://radcircle.com/about/">About</a></h2>
          			<h2><%= link_to "Team", team_path %></h2>

						<% if user_signed_in? %>
							<h2 class="create-nav-btn"><%= link_to 'Create', new_post_path %></h2>
							<h2 class="edit-nav-btn"><%= link_to 'Edit Account', edit_user_registration_path %></h2>
							<h2 class="logout-nav-btn"><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></h2>
						<% else %>
							<h2 class="login-nav-btn"><%= link_to 'Login', new_user_session_path %></h2>
							<h2 class="signup-nav-btn"><%= link_to 'Sign Up', new_user_registration_path %></h2>
						<% end %>

						<h2 class="feedback-nav-btn"><%= link_to 'Feedback', new_basecamp_path%></h2>
						<i class="fa fa-search search fa-5x"></i> <!-- click to open search, not fully working yet -->
						<!-- <i class="fa fa-envelope fa-5x"></i> -->


<!-- above = dropdown test -->
			</div>
</div>


<% [:notice, :alert].each do |level| %>
	<% if flash[level] %>
		<div class = "flash <%= level%>"><%= flash[level] %> </div>
	<%end%>
<%end%>

<section id="main">
  <div class="container-fluid">
  <%= yield %>
  <% if admin_signed_in? %>
    <%= admin_logged_in_msg %>
    <%else%>
    <%= user_logged_in_msg %>
  <%end%>
  </div>
</section>

<div class="col-xs-12 col-md-6 col-md-offset-3">
<a href="https://codeclimate.com/github/radcircle-dev/Peak"><img src="https://codeclimate.com/github/radcircle-dev/Peak.png"/></a>
</div>


</body>
</html>

app/views/pages/team.html.slim
.container-fluid
  #team-intro.row
    .col-md-12
      h1 This is Radcircle.
      p Meet the guys and gals behind it all.

  #team-members.row
    .col-md-3
      = image_tag 'team/mohammad.png'
      h2 Mohammad Azib
      p Founder &amp; CEO

    .col-md-3
      = image_tag 'team/filippo.png'
      h2 Filippo Fagnoni 
      p Editor

    .col-md-3
      = image_tag 'team/aj.png'
      h2 AJ D'Abbracci
      p Vice President, Technologies

    .col-md-3
      = image_tag 'team/connor-bw.jpg'
      h2 Connor Richardson 
      p Head of Operations

    .col-md-3
      = image_tag 'team/brandon-bw.png'
      h2 Brandon McKiddy 
      p Head of Editorials, Media

    .col-md-3
      = image_tag 'team/zac-bw.png'
      h2 Zac Hamidi 
      p Vice President, Electronic

    .col-md-3
      = image_tag 'team/austin-bw.jpg'
      h2 Austin Cisna 
      p Head, Platform Engineering

    .col-md-3
      = image_tag 'team/ben-bw.png'
      h2 Ben Strassman
      p Head, Longform Mediums

    .col-md-3
      = image_tag 'team/anita-bw.png'
      h2 Anita Nham
      p Senior Author

    .col-md-3
      = image_tag 'team/devon-bw.png'
      h2 Devon Phillips
      p Engineering

    .col-md-3
      = image_tag 'team/shannon-bw.png'
      h2 Shannon Zuber 
      p Author

    .col-md-3
      = image_tag 'team/michelle-bw.jpg'
      h2 Michelle Andrews
      p Author

    .col-md-3
      = image_tag 'team/reid-bw.jpg'
      h2 Reid Flynn 
      p Author

    .col-md-3
      = image_tag 'team/taylor-bw.jpg'
      h2 Taylor Glaser
      p Editorials

    .col-md-3
      = image_tag 'team/alec-bw.png'
      h2 Alec Sanderson
      p Editorials

    .col-md-3
      = image_tag 'team/marcos-bw.jpg'
      h2 Marcos Assor
      p Editorials

    .col-md-3
      = image_tag 'team/cassi-300-bw.jpg'
      h2 Cassi Kay
      p Editorials

    .col-md-3
      = image_tag 'team/jon-300-bw.jpg'
      h2 Jonathan Helm
      p Editorials

    .col-md-3
      = image_tag 'team/katie-300-bw.jpg'
      h2 Katie Fee
      p Head of Marketing

    .col-md-3
      = image_tag 'team/paisley-300-bw.png'
      h2 Paisley Elaine
      p Editorials

    .col-md-3
      = image_tag 'team/paul-bw.jpg'
      h2 Paul Millar
      p Advisor &amp; Castable Founder